projects:
  - id: "alex-brown-io"
    name: "AlexBrown.io"
    enabled: true
    notion:
      databaseId: "31e1a1f5565980068f8fc5b104994b4d"
    platforms:
      linkedin:
        accountId: "acc_xxxx"
        textProperty: "LinkedIn Text"
      x:
        accountId: "6998e4608ab8ae478b38fe22"
        textProperty: "X Text"
      instagram:
        accountId: "acc_zzz"
        textProperty: "Instagram Text"
  - id: "hdshot"
    name: "Hdshot.com"
    enabled: true
    notion:
      databaseId: "3281a1f556598084ae10d2ed45d4d545"
    platforms:
      pinterest:
        accountId: "69c0cf056cb7b8cf4c9041de"
